version: "3.7"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: ekyc-jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    networks:
      - ocr
networks:
  ocr:
    external: true