version: "3.7"
services:
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_KMS_KES_ENDPOINT=https://minio-kes:7373
      - MINIO_KMS_KES_CAPATH=/etc/default/minio/certs/ca.pem
      - MINIO_KMS_KES_CERT_FILE=/etc/default/minio/certs/minio-kes.pem
      - MINIO_KMS_KES_KEY_FILE=/etc/default/minio/certs/minio-kes-key.pem
      - MINIO_KMS_KES_KEY_NAME=minio
    volumes:
      - ../certs/minio/minio-key.pem:/root/.minio/certs/private.key:ro
      - ../certs/minio/minio.pem:/root/.minio/certs/public.crt:ro
      - ../certs/minio/ca.pem:/root/.minio/certs/CAs/public.crt:ro
      - ../certs/minio_kes/:/etc/default/minio/certs/:ro
      - /minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - ocr

networks:
  ocr:
    external: true


